#value要加双引号，否则容易读取出错，比如0030会读取为30

app:
  #由于gin的限制，可选值为：debug/test/release，不填或填其他值视为debug
  app-mode: "debug"
  http-port: "8000"

database:
  db-host: "localhost"
  db-port: "1433"
  db-name: "test"
  db-username: "sa"
  db-password: "028912"

jwt:
  #自定义密钥
  secret-key: "e7KF3k0dj3"
  #有效天数，登录后可以几天免登录
  validity-days: "30"

log:
  #日志文件的路径
  log-path: "d:/test/log"
  #在进行切割之前，日志文件的最大大小(MB)
  log-max-size: "10"
  #保留旧文件的最大个数
  log-max-backup: "100"
  #保留旧文件的最大天数
  log-max-age: "365"
  #是否压缩旧文件，默认为否
  log-compress: "False"

upload:
  #服务器上保存上传文件的路径
  storage-path: "D:/test/upload-files"
  #上传文件的最大尺寸(MB)，这里是50MB
  max-size: "50"

download:
  #对外暴露的文件访问路径
  access-path: "/download"

email:
  #发送邮件服务器，一般是smtp
  outgoing-mail-server: "smtp.qq.com"
  #端口，使用QQ邮箱时，发现587可以正常用，465用不了
  port: "587"
  account: "19725912@qq.com"
  #注意：QQ邮箱、88邮箱都需要使用授权码，而不是邮箱密码
  password: "ejusnukrlniabgdd"

#列表分页
paging:
  #单页默认条数
  default-page-size: "20"
  #单页最大条数
  max-page-size: "1000000"

#全局限流（采用令牌桶原理）
rate-limit:
  #每秒往令牌桶放XX个令牌，可以为小数
  limit: "1000"
  #令牌桶最大容量，必须为整数
  burst: "5000"

#数字验证码
captcha:
  #是否开启
  enabled: "true"
  #数字长度
  digit-length: "4"
  #图片宽度(px)
  image-width: "100"
  #图片高度(px)
  image-height: "40"
  #最大弯曲程度
  max-skew: "0.1"
  #背景里面小圆点的数量
  dot-count: "10"

#对象存储服务
oss:
  #选择存储方式
  type: "local"

ldap:
  server: "ldap://10.100.10.120:389"
  base-dn: "ou=中航国际北京公司,dc=avicbj,dc=ad"
  suffix: "@avicbj.ad"
  filter: "(&(objectClass=user))"
  #有访问权限的ou(organization unit)
  permitted-OUs: [ "公司领导", "公司专务", "公司总监", "综合管理和法律部","人力资源和海外机构事务部",
                   "财务管理部", "党建和纪检审计部", "储运管理部", "事业部管理委员会和水泥工程事业部",
                   "技术中心", "水泥工程市场一部", "水泥工程市场二部", "项目管理部", "工程项目执行部",
                   "水泥延伸业务部", "进口部/航空技术部", "成套业务一部", "成套业务二部", "成套业务三部",
                   "成套业务四部", "成套业务五部", "成套业务六部","国内企业管理部" ]
  attributes: [
    "cn",                #Common Name, 中文名，如：张三
    "distinguishedName", #DN, 区分名，如：[CN=张三, OU=综合管理和法律部, OU=中航国际北京公司, DC=avicbj, DC=ad]
    "sAMAccountName",    #登录名，如：x0020888、zhangsan
    "userPrincipalName", #UPN, 用户主体名称，如：x0020888@avicbj.ad
    "mail",              #邮箱，如：zhangsan@intl-bj.avic.com
  ]
