#value要加双引号，否则容易读取出错，比如0030会读取为30

app:
  app_mode: "debug"
  http_port: "8000"

database:
  db_host: "localhost"
  db_port: "1433"
  db_name: "test"
  db_username: "sa"
  db_password: "028912"
  #绝对不传给前端的数据库字段名
  omitted_columns: [ "password","created_at" ]

jwt:
  secret_key: "e7KF3k0dj3"
  #有效期(天)，登录后可以几天免登录
  validity_period: "14"

log:
  #日志文件的路径
  log_path: "d:/test/log"
  #在进行切割之前，日志文件的最大大小(MB)
  log_max_size: "10"
  #保留旧文件的最大个数
  log_max_backup: "100"
  #保留旧文件的最大天数
  log_max_age: "365"
  #是否压缩旧文件，默认为否
  log_compress: "False"

upload_files:
  #保存上传文件的完整路径
  full_path: "D:/test/upload_files"
  #上传文件的最大尺寸(MB)，这里是50MB
  max_size: "50"

email:
  #发送邮件服务器，一般是smtp
  outgoing_mail_server: "smtp.qq.com"
  #端口，使用QQ邮箱时，发现587可以正常用，465用不了
  port: "587"
  account: "19725912@qq.com"
  #注意：QQ邮箱、88邮箱都需要使用授权码，而不是邮箱密码
  password: "ejusnukrlniabgdd"

#列表分页
paging:
  #单页默认条数
  default_page_size: "20"
  max_page_size: "100"

initial_data:
  countries: [ "阿富汗","阿尔巴尼亚","阿尔及利亚","安道尔","安哥拉","安提瓜和巴布达","阿根廷","亚美尼亚","澳大利亚","奥地利","阿塞拜疆","巴哈马","巴林","孟加拉","巴巴多斯","白俄罗斯","立陶宛","伯利兹","贝宁","不丹","玻利维亚","波黑","博茨瓦纳","巴西","文莱","保加利亚","布基纳法索","布隆迪","柬埔寨","喀麦隆","加拿大","佛得角","乍得","智利","中国","哥伦比亚","科摩罗","刚果(布)","刚果(金)","哥斯达黎加","科特迪瓦","克罗地亚","古巴","塞浦路斯","捷克","丹麦","吉布提","多米尼加","厄瓜多尔","埃及","几内亚","厄立特里亚","爱沙尼亚","埃塞俄比亚","斐济","芬兰","法国","加蓬","冈比亚","格鲁吉亚","德国","加纳","希腊","阿曼","巴勒斯坦","韩国","老挝","马来西亚","缅甸","沙特阿拉伯","泰国","特国","印度尼西亚","阿联酋","东帝汶","哈萨克斯坦","卡塔尔","黎巴嫩","蒙古","尼泊尔","斯里兰卡","土耳其","乌兹别克斯坦","也门","以色列","约旦","叙利亚","巴基斯坦","朝鲜","菲律宾","吉尔吉斯斯坦","科威特","马尔代夫","日本","塔吉克斯坦","土库曼斯坦","新加坡","伊拉克","印度","越南","多哥","肯尼亚","利比亚","马拉维","毛里塔尼亚","纳米比亚","尼日尔","塞内加尔","苏丹","突尼斯","索莱托","卢旺达","马里","摩洛哥","尼日利亚","塞舌尔","索马里","乌干达","中非","赤道几内亚","几内亚比绍","利比里亚","马达加斯加","毛里求斯","莫桑比克","南苏丹","塞拉利昂","圣多美和普林西比","坦桑尼亚","赞比亚","北马其顿","波兰","拉脱维亚","罗马尼亚","挪威","瑞士","圣马力诺","乌克兰","匈牙利","爱尔兰","比利时","葡萄牙","塞尔维亚","斯洛伐克","西班牙","意大利","冰岛","英国","俄罗斯","荷兰","卢森堡","摩尔多瓦","瑞典","斯洛文尼亚","巴拿马","格拉纳达","萨尔瓦多","美国","特立尼达和多巴哥","多米尼克","墨西哥","牙买加","圭亚那","乌拉圭","巴西","苏里南","秘鲁","w国","基里巴斯","所罗门群岛","新西兰","巴布亚新几内亚","密克罗尼西亚","汤加","斐济"]
  provinces: [ "辽宁","河北" ]
  term_of_receipt_or_payment: [ "T/T(电汇)","L/C(信用证)" ]

  currency: [ "CNY" ]
  OrderForCurrency: [ ]

  TypeOfContract: [ ]
  TypeOfProject: [ ]
  StatusOfProject: [ ]
  OrderForStatusOfProject: [ ]
  NameOfBank: [ ]
  FundDirectionOfContract: [ ]
  OrderForFundDirectionOfContract: [ ]
  OurSignatory: [ ]
  SensitiveWord: [ ]
